name: Build Dotnet

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check-out
      - uses: actions/checkout@v4

      - name: Setup .NET 9.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
          
      - name: Install dependencies
        run: dotnet restore MircoOptimisations.sln
        
      - name: Build
        run: dotnet build --no-restore MircoOptimisations.sln
